#
# Default sample configuration for corebus services.
#
# Usually, you probably will not have to make much modification if you with
# to keep a purely synchronous application.
#
# This file must be loaded before other defined in this same directory.
#
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # Override this service in order to implement your own retry strategy.
    #
    corebus.retry_strategy.default:
        public: false
        class: MakinaCorpus\CoreBus\Implementation\RetryStrategy\DefaultRetryStrategy

    corebus.retry_strategy:
        alias: corebus.retry_strategy.default

    #
    # Warning: this service has an explicit dependency on the message broker.
    #
    MakinaCorpus\CoreBus\Implementation\RetryStrategy\RetryStrategyCommandBusDecorator:
        decorates: corebus.command.bus.synchronous
        decoration_priority: -5
        arguments: ['@.inner', '@corebus.retry_strategy', '@message_broker.message_broker']
