#
# Default sample configuration for corebus services.
#
# Usually, you probably will not have to make much modification if you with
# to keep a purely synchronous application.
#
# This file must be loaded before other defined in this same directory.
#
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MakinaCorpus\CoreBus\Bridge\Symfony\Command\CommandPushCommand:
        arguments: ['@corebus.command.bus.asynchronous', '@corebus.command.bus.synchronous', '@normalization.serializer', '@normalization.name_map']
        tags: ['console.command']

    MakinaCorpus\CoreBus\Bridge\Symfony\Command\CommandWorkerCommand:
        arguments: ['@corebus.command.consumer', '@?message_broker.consumer_factory', '@?corebus.retry_strategy']
        tags:
            - { name: "monolog.logger", channel: "corebus" }
            - { name: "console.command"}
