#
# Default sample configuration for corebus services.
#
# Integrates with services from makinacorpus/goat package when plugged
# with the provided Symfony bundle.
#
services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    #
    # Plugs event store on command bus, transparently store all dispatched
    # commands into the event store.
    #

    corebus.event_store_info_extractor.attribute:
        public: false
        class: MakinaCorpus\CoreBus\Bridge\EventStore\AttributeEventInfoExtrator
        tags: ['app.event_info']

    corebus.event_store_info_extractor.legacy:
        public: false
        class: MakinaCorpus\CoreBus\Bridge\EventStore\LegacyAggregateEventInfoExtrator
        tags: ['app.event_info']

    corebus.event_store_info_extractor:
        public: false
        class: MakinaCorpus\CoreBus\Bridge\EventStore\EventInfoExtratorChain
        arguments: [[]]

    MakinaCorpus\CoreBus\Bridge\EventStore\EventStoreCommandConsumerDecorator:
        decorates: corebus.command.consumer
        decoration_priority: -5
        # Last parameter is runtime project player.
        arguments: ['@.inner', '@event_store.event_store', '@corebus.event_store_info_extractor', null]
