#
# Default sample configuration for corebus services.
#
# Usually, you probably will not have to make much modification if you with
# to keep a purely synchronous application.
#
# This file must be loaded before other defined in this same directory.
#
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # Integration
    #

    corebus.argument_resolver:
        class: MakinaCorpus\ArgumentResolver\DefaultArgumentResolver
        tags: [{ name: argument_resolver, id: corebus }]

    #
    # Transactions manager
    #

    corebus.transaction.manager.null:
        class: MakinaCorpus\CoreBus\Transaction\NullTransactionManager

    corebus.transaction.manager:
        alias: corebus.transaction.manager.null

    corebus.event_buffer.manager.array:
        class: MakinaCorpus\CoreBus\EventBus\Buffer\ArrayEventBufferManager

    corebus.event_buffer.manager:
        alias: corebus.event_buffer.manager.array

    #
    # Event bus and event listener locator.
    #

    corebus.event.listener.locator.container:
        class: MakinaCorpus\CoreBus\EventBus\Bus\ContainerEventListenerLocator
        arguments: [[], null, '@corebus.argument_resolver']

    corebus.event.listener.locator:
        alias: corebus.event.listener.locator.container

    corebus.event.bus.null:
        class: MakinaCorpus\CoreBus\EventBus\Bus\NullEventBus

    corebus.event.bus.memory:
        class: MakinaCorpus\CoreBus\EventBus\Bus\MemoryEventBus
        arguments:
            - "@corebus.event.listener.locator"

    corebus.event.bus.internal:
        alias: corebus.event.bus.memory

    corebus.event.bus.external:
        alias: corebus.event.bus.null

    #
    # Command buses.
    #

    corebus.command.bus.synchronous:
        class: MakinaCorpus\CoreBus\CommandBus\Bus\PassthroughCommandBus
        arguments:
            - "@corebus.command.consumer"
        tags:
            - { name: "monolog.logger", channel: "corebus" }

    # Default asynchronous command bus cannot have the consumer as dependency
    # as it would create circular dependencies, that actually highlights deeper
    # concerns: the consumer needs the command bus for sending responses, the
    # bus cannot therefore need the consumer for passing messages throught.
    corebus.command.bus.asynchronous:
        class: MakinaCorpus\CoreBus\CommandBus\Bus\NullCommandConsumer
        tags:
            - { name: "monolog.logger", channel: "corebus" }

    #
    # Authorization checker
    #

    corebus.command.authorization_checker:
        class: MakinaCorpus\CoreBus\CommandBus\Authorization\CommandAuthorizationCheckerChain
        arguments: []

    corebus.command.bus.asynchronous.authorization:
        class: MakinaCorpus\CoreBus\CommandBus\Bus\AuthorizationCommandBusDecorator
        decorates: corebus.command.bus.asynchronous
        arguments: ['@corebus.command.authorization_checker', '@.inner']

    corebus.command.bus.synchronous.authorization:
        class: MakinaCorpus\CoreBus\CommandBus\Bus\AuthorizationCommandBusDecorator
        decorates: corebus.command.bus.synchronous
        arguments: ['@corebus.command.authorization_checker', '@.inner']

    #
    # Command consumer and command handler locator.
    #

    corebus.command.handler.locator.container:
        class: MakinaCorpus\CoreBus\CommandBus\Bus\ContainerCommandHandlerLocator
        arguments: [[], null, '@corebus.argument_resolver']

    corebus.command.handler_locator:
        alias: corebus.command.handler.locator.container

    corebus.command.consumer.default:
        class: MakinaCorpus\CoreBus\CommandBus\Consumer\DefaultCommandConsumer
        arguments:
            - "@corebus.command.handler_locator"
        tags:
            - { name: "monolog.logger", channel: "corebus" }

    corebus.command.consumer.transactional:
        class: MakinaCorpus\CoreBus\CommandBus\Consumer\TransactionalCommandConsumer
        decorates: corebus.command.consumer.default
        decoration_priority: 100
        arguments:
            - "@.inner"
            - "@corebus.event.bus.internal"
            - "@corebus.event.bus.external"
            - "@corebus.event_buffer.manager"
            - "@corebus.transaction.manager"
        tags:
            - { name: "monolog.logger", channel: "corebus" }

    corebus.command.consumer.reply_to:
        class: MakinaCorpus\CoreBus\CommandBus\Consumer\ReplyToCommandConsumer
        decorates: corebus.command.consumer.default
        decoration_priority: 50
        arguments:
            - "@.inner"
            - "@corebus.command.bus.asynchronous"

    corebus.command.consumer:
        alias: corebus.command.consumer.default

    #
    # Aliases to use and Symfony autowiring.
    #

    MakinaCorpus\CoreBus\CommandBus\CommandAuthorizationChecker:
        alias: corebus.command.authorization_checker

    MakinaCorpus\CoreBus\EventBus\EventBus:
        alias: corebus.command.consumer.transactional

    MakinaCorpus\CoreBus\CommandBus\CommandConsumer:
        alias: corebus.command.consumer

    MakinaCorpus\CoreBus\CommandBus\CommandBus:
        alias: corebus.command.bus.asynchronous

    MakinaCorpus\CoreBus\CommandBus\SynchronousCommandBus:
        alias: corebus.command.bus.synchronous

    #
    # HTTP default controller, unused if routes are not registered.
    #

    MakinaCorpus\CoreBus\Bridge\Symfony\Controller\CommandController:
        tags: ['controller.service_arguments']
